"""Add explanation to recommendation

Revision ID: 02c7f7634ff6
Revises: c48ed700e549
Create Date: 2026-07-11 11:53:12.000787

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '02c7f7634ff6'
down_revision: str | None = 'c48ed700e549'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('explanation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'explanation')
    # ### end Alembic commands ###
