"""Add explanation to recommendation

Revision ID: 02c7f7634ff6
Revises: c48ed700e549
Create Date: 2026-07-11 11:53:12.000787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c7f7634ff6'
down_revision: Union[str, None] = 'c48ed700e549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('explanation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'explanation')
    # ### end Alembic commands ###
