"""add_premium_catalog_fields

Revision ID: 5935312b3c87
Revises: 02c7f7634ff6
Create Date: 2026-07-12 11:55:10.905724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5935312b3c87'
down_revision: Union[str, None] = '02c7f7634ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_table('product_variant',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=50), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variant_product_id'), 'product_variant', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variant_sku'), 'product_variant', ['sku'], unique=True)
    op.add_column('product', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('warranty', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('seller', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('shipping_time', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('specifications', sa.JSON(), nullable=True))
    op.add_column('product', sa.Column('seo_title', sa.String(length=150), nullable=True))
    op.add_column('product', sa.Column('meta_description', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('keywords', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('alt_text', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('badge', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('availability_status', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product', sa.Column('discount_percent', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('savings', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('popularity_score', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('trend_score', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('embedding_vector_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_column('product', 'embedding_vector_id')
    op.drop_column('product', 'trend_score')
    op.drop_column('product', 'popularity_score')
    op.drop_column('product', 'sentiment_score')
    op.drop_column('product', 'savings')
    op.drop_column('product', 'discount_percent')
    op.drop_column('product', 'mrp')
    op.drop_column('product', 'availability_status')
    op.drop_column('product', 'badge')
    op.drop_column('product', 'alt_text')
    op.drop_column('product', 'keywords')
    op.drop_column('product', 'meta_description')
    op.drop_column('product', 'seo_title')
    op.drop_column('product', 'specifications')
    op.drop_column('product', 'shipping_time')
    op.drop_column('product', 'seller')
    op.drop_column('product', 'warranty')
    op.drop_column('product', 'barcode')
    op.drop_column('product', 'sku')
    op.drop_index(op.f('ix_product_variant_sku'), table_name='product_variant')
    op.drop_index(op.f('ix_product_variant_product_id'), table_name='product_variant')
    op.drop_table('product_variant')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_table('product_image')
    # ### end Alembic commands ###
